#!/usr/bin/env bash
# Start one or more DevNet nodes on the current machine.
# Running this script RESETS the specified nodes (wipes their data).
#
# Usage:
#   ./start-single.sh <node...> <image>
#
# Examples:
#   ./start-single.sh val-0 val-1 ghcr.io/abfoundationglobal/abcore:v1.13.15  # server-1
#   ./start-single.sh val-4 ghcr.io/abfoundationglobal/abcore:v1.13.15         # server-3
#   ./start-single.sh rpc-0 ghcr.io/abfoundationglobal/abcore:v1.13.15         # server-4
#
# Required environment variables:
#   GENESIS_FILE   — path to genesis.json (generated by generate-genesis.sh and scp'd here)
#
# Optional environment variables:
#   DATA_DIR       — node data root (default: ./data)
#   CHAIN_ID       — devnet chain ID (default: 17140, must match genesis)
#   LOG_LEVEL      — geth verbosity 1-5 (default: 3)
#   DOCKER_HOST_IP — IP containers use to reach host ports (default: auto-detected)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib.sh"

# ---------------------------------------------------------------------------
# Parse arguments: <node...> <image>  (image is always last)
# ---------------------------------------------------------------------------
if [[ $# -lt 2 ]]; then
    error "Usage: $0 <node...> <image>"
    echo "  e.g. $0 val-0 val-1 ghcr.io/abfoundationglobal/abcore:v1.13.15"
    echo "  e.g. $0 val-4 ghcr.io/abfoundationglobal/abcore:v1.13.15"
    exit 1
fi

IMAGE="${@: -1}"
NODES=("${@:1:$(( $# - 1 ))}")

for node in "${NODES[@]}"; do
    if ! node_is_valid_name "$node"; then
        error "Unknown node name: '$node'. Valid names: ${VALID_NODES[*]}"
        exit 1
    fi
done

if [[ -z "${GENESIS_FILE:-}" ]]; then
    error "GENESIS_FILE is required."
    echo "  Generate it with: ./generate-genesis.sh"
    echo "  Then set: GENESIS_FILE=/path/to/genesis.json"
    exit 1
fi

if [[ ! -f "$GENESIS_FILE" ]]; then
    error "GENESIS_FILE not found: $GENESIS_FILE"
    exit 1
fi

CHAIN_ID="${CHAIN_ID:-17140}"
LOG_LEVEL="${LOG_LEVEL:-3}"
KEYSTORES_DIR="$SCRIPT_DIR/keystores"

section "Starting nodes: ${NODES[*]}"
info "Image      : $IMAGE"
info "Genesis    : $GENESIS_FILE"
info "Data dir   : $DATA_DIR"
info "Chain ID   : $CHAIN_ID"

# ---------------------------------------------------------------------------
# Pre-flight: verify keystores for validator nodes
# ---------------------------------------------------------------------------
section "Checking keystores"

for node in "${NODES[@]}"; do
    if node_is_validator "$node"; then
        ks="$KEYSTORES_DIR/$node.json"
        addr_file="$KEYSTORES_DIR/$node.address"
        if [[ ! -f "$ks" ]]; then
            error "Keystore not found: $ks"
            error "See keystores/README.md — copy the keystore files before running."
            exit 1
        fi
        if [[ ! -f "$addr_file" ]]; then
            error "Address file not found: $addr_file"
            exit 1
        fi
        info "  $node → $(cat "$addr_file")"
    fi
done

# ---------------------------------------------------------------------------
# Step 0: pull image (must happen before reset, which uses the image to wipe
# root-owned chaindata via a throw-away container)
# ---------------------------------------------------------------------------
section "Pulling image"

if docker image inspect "$IMAGE" &>/dev/null; then
    info "Image $IMAGE already present locally, skipping pull."
else
    info "Pulling $IMAGE ..."
    docker pull "$IMAGE"
fi

# ---------------------------------------------------------------------------
# Step 1: stop existing containers and wipe data for specified nodes
# ---------------------------------------------------------------------------
section "Reset: stopping containers and wiping data"

for node in "${NODES[@]}"; do
    stop_node "$node"
done

for node in "${NODES[@]}"; do
    local_dir="$(node_datadir "$node")"
    if [[ -d "$local_dir" ]]; then
        warn "Removing data: $local_dir"
        # chaindata may be root-owned (geth init runs as root in Docker)
        docker run --rm -v "$local_dir:/target" --entrypoint sh \
            "$IMAGE" -c "rm -rf /target/*" 2>/dev/null || sudo rm -rf "$local_dir"
        rm -rf "$local_dir"
    fi
    mkdir -p "$local_dir/keystore"
done

# ---------------------------------------------------------------------------
# Step 2: install keystores
# ---------------------------------------------------------------------------
section "Installing keystores"

for node in "${NODES[@]}"; do
    if node_is_validator "$node"; then
        local_dir="$(node_datadir "$node")"
        addr=$(cat "$KEYSTORES_DIR/$node.address")
        cp "$KEYSTORES_DIR/$node.json" "$local_dir/keystore/$node.json"
        echo "" > "$local_dir/password.txt"
        echo "$addr" > "$local_dir/address.txt"
        info "  $node → $addr"
    fi
done

# ---------------------------------------------------------------------------
# Step 2: init chaindata from genesis
# ---------------------------------------------------------------------------
section "Initialising chaindata"

for node in "${NODES[@]}"; do
    local_dir="$(node_datadir "$node")"
    info "Initialising $node ..."
    output=$(docker run --rm \
        -v "$local_dir:/data" \
        -v "$GENESIS_FILE:/genesis.json:ro" \
        --entrypoint geth \
        "$IMAGE" \
        init --datadir /data /genesis.json 2>&1) || {
        error "geth init failed for $node"
        echo "$output" >&2
        exit 1
    }
    echo "$output" | grep -E "(ERR|WARN|Fatal)" || true
done

# ---------------------------------------------------------------------------
# Step 3: start containers
# ---------------------------------------------------------------------------
section "Starting containers"

for node in "${NODES[@]}"; do
    local_dir="$(node_datadir "$node")"
    rpc_port="$(node_rpc_port "$node")"
    p2p_port="$(node_p2p_port "$node")"
    name="$(node_container_name "$node")"

    local_extra_flags=()
    if node_is_validator "$node"; then
        addr=$(cat "$local_dir/address.txt")
        local_extra_flags+=(
            "--mine"
            "--unlock" "$addr"
            "--password" "/data/password.txt"
            "--miner.etherbase" "$addr"
            "--allow-insecure-unlock"
        )
    fi

    info "Starting $node (container: $name, RPC :$rpc_port, P2P :$p2p_port) ..."
    docker run -d \
        --name "$name" \
        --restart unless-stopped \
        -v "$local_dir:/data" \
        -p "127.0.0.1:${rpc_port}:8545" \
        -p "${p2p_port}:${p2p_port}/tcp" \
        -p "${p2p_port}:${p2p_port}/udp" \
        --entrypoint geth \
        "$IMAGE" \
        --datadir /data \
        --networkid "$CHAIN_ID" \
        --port "$p2p_port" \
        --http \
        --http.addr "0.0.0.0" \
        --http.port 8545 \
        --http.api "eth,net,web3,clique,admin,personal,debug" \
        --http.corsdomain "*" \
        --ws \
        --ws.addr "0.0.0.0" \
        --ws.port 8546 \
        --ws.api "eth,net,web3,clique,admin,personal" \
        --syncmode full \
        --gcmode archive \
        --verbosity "$LOG_LEVEL" \
        --nat "extip:$DOCKER_HOST_IP" \
        "${local_extra_flags[@]}" \
        > /dev/null
done

# ---------------------------------------------------------------------------
# Step 4: wait for RPC and report status
# ---------------------------------------------------------------------------
section "Waiting for RPC"

for node in "${NODES[@]}"; do
    rpc_port="$(node_rpc_port "$node")"
    name="$(node_container_name "$node")"
    if ! wait_for_rpc "$rpc_port" 30; then
        error "$node RPC did not respond within 30s"
        echo "  Check: docker logs $name"
        exit 1
    fi
    bn=$(block_number "$rpc_port")
    info "  $node ready (block=$bn)"
done

echo ""
info "Nodes started on this machine: ${NODES[*]}"
echo ""
echo "  Enode (for P2P wiring by Jenkins):"
for node in "${NODES[@]}"; do
    rpc_port="$(node_rpc_port "$node")"
    p2p_port="$(node_p2p_port "$node")"
    enode=$(rpc_call "$rpc_port" admin_nodeInfo '[]' \
        | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('result',{}).get('enode',''))" 2>/dev/null || echo "")
    enode_rewritten=$(echo "$enode" | sed -E "s|@[^:]+:[0-9]+(\?.*)?$|@${DOCKER_HOST_IP}:${p2p_port}|")
    printf "  %-8s %s\n" "$node" "$enode_rewritten"
done
echo ""
echo "  Logs  : docker logs devnet-<node>"
echo "  Status: ./status-single.sh ${NODES[*]}"
