#!/usr/bin/env bash
# Test: downtime → misdemeanor → felony → breathe-with-jailed-validator → unjail
#
# Uses genesis-contracts-slash-test.json (generated from abchain-local with
# reduced thresholds: misdemeanorThreshold=5, felonyThreshold=15,
# downtimeJailTime=60 s, felonyJailTime=120 s) so the complete punishment
# and unjail cycle finishes in ~8–10 minutes on a 3-validator local network.
#
# Critical path exercised:
#   Parlia → slash(val3) system tx → SlashIndicator.downtimeSlash()
#   → misdemeanor() → felony() → StakeHub.jailValidator()
#   → breathe block → updateValidatorSetV2 (with val3 excluded)  ← key risk
#   → unjail(val3) → breathe block → updateValidatorSetV2 (val3 re-enters)
#
# This mirrors the risk flagged in abcore-v2#112: an untested code path where
# a jailed validator in the empty-set bootstrap scenario could cause chain
# stalls in Finalize() analogous to the validatorExtraSet / SystemReward bugs.
set -euo pipefail

# ── Configuration ──────────────────────────────────────────────────────────────
BREATHE_INTERVAL=30   # geth --override.breatheblockinterval (seconds)
SLASH_POLL=4          # seconds between getSlashIndicator polls while waiting
MISDEMEANOR_THRESHOLD=5
FELONY_THRESHOLD=15
DOWNTIME_JAIL_SECS=60

# ── Paths ──────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
GETH="$REPO_ROOT/build/bin/geth"
DATA_DIR="$SCRIPT_DIR/data"
BLS_PROOF_SRC="$REPO_ROOT/script/test/upgrade-drill/bls_proof/main.go"

STAKEHUB="0x0000000000000000000000000000000000002002"
SLASHINDICATOR="0x0000000000000000000000000000000000001001"
VALCONTRACT="0x0000000000000000000000000000000000001000"

# ── Colors ─────────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'

GETH_PIDS=()
BLS_TMPDIR=""
FAILED=0

pass() { echo -e "${GREEN}  PASS  $*${NC}"; }
fail() { echo -e "${RED}  FAIL  $*${NC}"; FAILED=1; }
log()  { echo -e "${YELLOW}==> $*${NC}"; }

# ── Cleanup ────────────────────────────────────────────────────────────────────
cleanup() {
    if [ ${#GETH_PIDS[@]} -gt 0 ]; then
        for pid in "${GETH_PIDS[@]}"; do
            kill "$pid" 2>/dev/null || true
        done
        for pid in "${GETH_PIDS[@]}"; do
            local j=0
            while kill -0 "$pid" 2>/dev/null && [ $j -lt 8 ]; do sleep 1; ((j++)); done
            kill -9 "$pid" 2>/dev/null || true
        done
    fi
    log "Removing generated data..."
    rm -rf "$DATA_DIR" "$SCRIPT_DIR/genesis.json" \
           "$SCRIPT_DIR/config/genesis.json" "$SCRIPT_DIR/config/password.txt"
    [ -n "${BLS_TMPDIR:-}" ] && rm -rf "$BLS_TMPDIR"
}
trap cleanup EXIT

# ── Pre-flight ─────────────────────────────────────────────────────────────────
if [ ! -x "$GETH" ]; then
    echo -e "${RED}Error: geth not found at $GETH — run 'make geth' first${NC}"; exit 1
fi
if [ ! -f "$BLS_PROOF_SRC" ]; then
    echo -e "${RED}Error: bls_proof not found at $BLS_PROOF_SRC${NC}"; exit 1
fi
if [ ! -f "$SCRIPT_DIR/genesis-contracts-slash-test.json" ]; then
    echo -e "${RED}Error: genesis-contracts-slash-test.json not found.${NC}"
    echo "  It is generated by 'make build' in core/systemcontracts/parliagenesis/"
    echo "  (requires abchain-local with reduced slash parameters)."
    exit 1
fi
command -v python3 >/dev/null || { echo -e "${RED}python3 required${NC}"; exit 1; }
command -v go     >/dev/null || { echo -e "${RED}go toolchain required${NC}"; exit 1; }

# ── Step 1: Setup 3-validator network with slash-test genesis ──────────────────
log "Setting up 3-validator network (genesis: slash-test thresholds)..."
export GENESIS_CONTRACTS_JSON="$SCRIPT_DIR/genesis-contracts-slash-test.json"
"$SCRIPT_DIR/01-setup.sh" 3

# ── Step 2: Build bls_proof and generate BLS keys ─────────────────────────────
log "Building bls_proof and generating BLS keys (chain-id=7140)..."
BLS_TMPDIR=$(mktemp -d)
BLS_PROOF_BIN="$BLS_TMPDIR/bls_proof"
BLS_PW="blspassword"
(cd "$REPO_ROOT" && go build -o "$BLS_PROOF_BIN" "$BLS_PROOF_SRC")

declare -a BLS_PUBKEY=()
declare -a BLS_PROOF_HEX=()
for n in 1 2 3; do
    addr=$(cat "$DATA_DIR/validator-$n/address.txt" | tr '[:upper:]' '[:lower:]')
    bls_dir="$BLS_TMPDIR/validator-$n"
    mkdir -p "$bls_dir"
    pwfile="$bls_dir/bls-pw.txt"; printf '%s\n' "$BLS_PW" > "$pwfile"
    "$GETH" bls account new --datadir "$bls_dir" --blspassword "$pwfile" 2>/dev/null
    keystore=$(find "$bls_dir/bls/keystore" -name "keystore-*.json" 2>/dev/null | head -1)
    [ -n "$keystore" ] || { echo -e "${RED}No BLS keystore for validator-$n${NC}"; exit 1; }
    proof_out=$("$BLS_PROOF_BIN" -keystore "$keystore" -password "$BLS_PW" \
        -operator "$addr" -chainid 7140)
    BLS_PUBKEY[$n]=$(echo "$proof_out" | grep '^PUBKEY=' | cut -d= -f2 | tr -d '[:space:]')
    BLS_PROOF_HEX[$n]=$(echo "$proof_out" | grep '^PROOF='  | cut -d= -f2 | tr -d '[:space:]')
    [ ${#BLS_PUBKEY[$n]} -eq 96  ] || { echo -e "${RED}validator-$n: bad BLS pubkey length${NC}"; exit 1; }
    [ ${#BLS_PROOF_HEX[$n]} -eq 194 ] || { echo -e "${RED}validator-$n: bad BLS proof length${NC}"; exit 1; }
    log "  validator-$n BLS pubkey: ${BLS_PUBKEY[$n]:0:12}..."
done

# ── Step 3: Start all 3 validators ────────────────────────────────────────────
log "Starting 3 validators (breatheBlockInterval=${BREATHE_INTERVAL}s)..."

_start_validator() {
    local n=$1
    local port=$((8544 + n))
    local p2p=$((30302 + n))
    local vdir="$DATA_DIR/validator-$n"
    local addr; addr=$(cat "$vdir/address.txt")
    local extra_flags=()
    [ -n "${BOOTNODE:-}" ] && extra_flags+=(--bootnodes "$BOOTNODE")

    nohup "$GETH" \
        --datadir "$vdir" \
        --networkid 7140 \
        --port "$p2p" \
        --http --http.addr "127.0.0.1" --http.port "$port" \
        --http.api "eth,net,web3,debug,parlia,admin,personal" \
        --http.corsdomain "*" \
        --ws --ws.addr "127.0.0.1" --ws.port "$((port + 1000))" \
        --ws.api "eth,net,web3,debug,parlia,admin,personal" \
        --nat extip:127.0.0.1 \
        --maxpeers 10 \
        --mine \
        --unlock "$addr" \
        --password "$vdir/password.txt" \
        --miner.etherbase "$addr" \
        --allow-insecure-unlock \
        --syncmode "full" \
        --gcmode "archive" \
        --verbosity 3 \
        --override.breatheblockinterval "$BREATHE_INTERVAL" \
        ${extra_flags[@]+"${extra_flags[@]}"} \
        > "$vdir/geth.log" 2>&1 &

    local pid=$!
    GETH_PIDS+=("$pid")
    echo "$pid" > "$vdir/geth.pid"
    log "  validator-$n: PID=$pid  RPC=:$port"
}

_start_validator 1
sleep 5
BOOTNODE=""
for i in $(seq 1 15); do
    if [ -S "$DATA_DIR/validator-1/geth.ipc" ]; then
        BOOTNODE=$("$GETH" attach --exec "admin.nodeInfo.enode" \
            "$DATA_DIR/validator-1/geth.ipc" 2>/dev/null \
            | tr -d '"' | sed 's/?.*$//') && [ -n "$BOOTNODE" ] && break
    fi
    sleep 2
done
[ -n "$BOOTNODE" ] && log "  validator-1 enode: ${BOOTNODE:0:40}..."
for n in 2 3; do _start_validator "$n"; sleep 2; done

log "Wiring peer mesh..."
ENODES=()
for n in 1 2 3; do
    e=""
    for attempt in $(seq 1 20); do
        e=$("$GETH" attach --exec "admin.nodeInfo.enode" \
            "$DATA_DIR/validator-$n/geth.ipc" 2>/dev/null \
            | tr -d '"' | sed 's/?.*$//') || true
        [ -n "$e" ] && break; sleep 2
    done
    [ -n "$e" ] || { echo -e "${RED}validator-$n enode unavailable${NC}"; exit 1; }
    ENODES+=("$e")
done
for i in 1 2 3; do
    for j in 1 2 3; do
        [ $i -eq $j ] && continue
        "$GETH" attach --exec "admin.addPeer(\"${ENODES[$((j-1))]}\") + ''" \
            "$DATA_DIR/validator-$i/geth.ipc" 2>/dev/null >/dev/null || true
    done
done

log "Waiting for all 3 RPC endpoints..."
for n in 1 2 3; do
    port=$((8544 + n))
    for i in $(seq 1 30); do
        resp=$(curl -sf -X POST "http://127.0.0.1:$port" \
            -H 'Content-Type: application/json' \
            -d '{"jsonrpc":"2.0","method":"eth_blockNumber","id":1}' 2>/dev/null || true)
        echo "$resp" | grep -q '"result"' && break
        [ $i -eq 30 ] && { echo -e "${RED}validator-$n RPC never ready${NC}"; exit 1; }
        sleep 1
    done
    log "  validator-$n RPC ready"
done

IPC1="$DATA_DIR/validator-1/geth.ipc"
IPC3="$DATA_DIR/validator-3/geth.ipc"

_attach() { "$GETH" attach --exec "$1" "$IPC1" 2>/dev/null | tr -d '"' | tr -d '\r'; }
_attach3() { "$GETH" attach --exec "$1" "$IPC3" 2>/dev/null | tr -d '"' | tr -d '\r'; }

_wait_mined() {
    local tx="$1" label="$2"
    for i in $(seq 1 20); do
        sleep 3
        local st
        st=$(_attach "(function(){var r=eth.getTransactionReceipt('${tx}');return r?r.status:'pending';})()")
        case "$st" in
            0x1|1) pass "$label  (tx=${tx:0:14}…)"; return 0 ;;
            0x0|0) fail "$label reverted  (tx=${tx:0:14}…)"; return 1 ;;
        esac
    done
    fail "$label not mined after 60 s  (tx=${tx:0:14}…)"
    return 1
}

_tip() { _attach "eth.blockNumber" | grep -o '[0-9]*' | head -1; }

_has_breathe() {
    local window="${1:-50}"
    local count
    count=$(_attach \
"(function(){var sel=web3.sha3('updateValidatorSetV2(address[],uint64[],bytes[])').slice(2,10);
var n=eth.blockNumber,c=0;
for(var i=n;i>n-${window}&&i>=0;i--){
  var b=eth.getBlock(i,true);
  if(b&&b.transactions.some(function(tx){return tx.to&&tx.to.toLowerCase()==='${VALCONTRACT}'&&tx.input&&tx.input.slice(2,10)===sel;}))c++;
}return c;})()")
    [ "${count:-0}" -gt 0 ]
}

_election_count() {
    local sel
    sel=$(_attach "web3.sha3('getValidatorElectionInfo(uint256,uint256)').slice(2,10)")
    local zeros="0000000000000000000000000000000000000000000000000000000000000000"
    local raw; raw=$(_attach "eth.call({to:'${STAKEHUB}',data:'0x${sel}${zeros}${zeros}'})")
    python3 -c "d='${raw}'.replace('0x','').replace('\"','');print(int(d[192:256],16) if len(d)>=256 else 0)" 2>/dev/null || echo 0
}

_slash_count() {
    local addr="${1#0x}"
    local sel; sel=$(_attach "web3.sha3('getSlashIndicator(address)').slice(2,10)")
    local padded; padded="$(printf '%064s' "$addr" | tr ' ' '0')"
    local raw; raw=$(_attach "eth.call({to:'${SLASHINDICATOR}',data:'0x${sel}${padded}'})")
    python3 -c "
d='${raw}'.replace('0x','').replace('\"','')
if len(d)<128: print(0)
else: print(int(d[64:128],16))
" 2>/dev/null || echo 0
}

_is_jailed() {
    local addr="${1#0x}"
    local sel; sel=$(_attach "web3.sha3('getValidatorBasicInfo(address)').slice(2,10)")
    local padded; padded="$(printf '%064s' "$addr" | tr ' ' '0')"
    local raw; raw=$(_attach "eth.call({to:'${STAKEHUB}',data:'0x${sel}${padded}'})")
    python3 -c "
d='${raw}'.replace('0x','').replace('\"','')
# returns (uint256 createdTime, bool jailed, uint256 jailUntil)
# jailed is at bytes 32-64 (after createdTime)
if len(d)<192: print('false')
else: print('true' if int(d[64:128],16)!=0 else 'false')
" 2>/dev/null || echo "false"
}

_jail_until() {
    local addr="${1#0x}"
    local sel; sel=$(_attach "web3.sha3('getValidatorBasicInfo(address)').slice(2,10)")
    local padded; padded="$(printf '%064s' "$addr" | tr ' ' '0')"
    local raw; raw=$(_attach "eth.call({to:'${STAKEHUB}',data:'0x${sel}${padded}'})")
    python3 -c "
d='${raw}'.replace('0x','').replace('\"','')
if len(d)<192: print(0)
else: print(int(d[128:192],16))
" 2>/dev/null || echo 0
}

# ── Step 4: Wait for StakeHub init ────────────────────────────────────────────
log "Precomputing function selectors..."
CREATE_SEL=$(_attach "web3.sha3('createValidator(address,bytes,bytes,(uint64,uint64,uint64),(string,string,string,string))').slice(2,10)") || true
DEL_SEL=$(_attach  "web3.sha3('delegate(address,bool)').slice(2,10)") || true
LOCK_SEL=$(_attach "web3.sha3('LOCK_AMOUNT()').slice(2,10)") || true
MIN_SEL=$(_attach  "web3.sha3('minSelfDelegationBNB()').slice(2,10)") || true

log "Waiting for StakeHub initialization..."
MIN_WEI=0
for i in $(seq 1 60); do
    MIN_RAW=$(_attach "eth.call({to:'${STAKEHUB}',data:'0x${MIN_SEL}'})") || true
    MIN_WEI=$(python3 -c "print(int('${MIN_RAW}'.replace('0x','') or '0',16))" 2>/dev/null || echo 0)
    [ "${MIN_WEI:-0}" != "0" ] && break
    [ $i -eq 60 ] && { echo -e "${RED}StakeHub not initialized after 60 s${NC}"; exit 1; }
    sleep 1
done
LOCK_RAW=$(_attach "eth.call({to:'${STAKEHUB}',data:'0x${LOCK_SEL}'})") || true
LOCK_WEI=$(python3 -c "print(int('${LOCK_RAW}'.replace('0x','') or '0',16))" 2>/dev/null || echo 0)
[ "${LOCK_WEI:-0}" != "0" ] || { echo -e "${RED}LOCK_AMOUNT returned empty${NC}"; exit 1; }
TX_VALUE_HEX=$(python3 -c "print(hex(${MIN_WEI}+${LOCK_WEI}))")
log "  LOCK_AMOUNT=${LOCK_WEI} wei  minSelfDel=${MIN_WEI} wei"

_build_create_calldata() {
    local n=$1
    local addr; addr=$(cat "$DATA_DIR/validator-$n/address.txt" | tr '[:upper:]' '[:lower:]')
    local addr_hex="${addr#0x}"
    local pubkey_hex="${BLS_PUBKEY[$n]}"
    local proof_hex="${BLS_PROOF_HEX[$n]#0x}"
    python3 - <<PY
def to32(n): return n.to_bytes(32,'big').hex()
def enc_bytes(h):
    d=bytes.fromhex(h); sz=len(d); pad=(32-sz%32)%32
    return to32(sz)+h+'00'*pad
def enc_str(s): return enc_bytes(s.encode().hex())
p_addr='00'*12+'${addr_hex}'
n=${n}
vote_enc=enc_bytes('${pubkey_hex}')
bls_enc=enc_bytes('${proof_hex}')
commission_enc=to32(10)+to32(100)+to32(5)
mon_enc=enc_str(f'Val{n}')
id_enc=enc_str(''); ws_enc=enc_str(''); det_enc=enc_str('')
inner_head=4*32
mon_off=inner_head
id_off=mon_off+len(mon_enc)//2
ws_off=id_off+len(id_enc)//2
det_off=ws_off+len(ws_enc)//2
desc_enc=(to32(mon_off)+to32(id_off)+to32(ws_off)+to32(det_off)
          +mon_enc+id_enc+ws_enc+det_enc)
HEAD=32+32+32+96+32
vote_off=HEAD
bls_off=vote_off+len(vote_enc)//2
desc_off=bls_off+len(bls_enc)//2
head=(p_addr+to32(vote_off)+to32(bls_off)+commission_enc+to32(desc_off))
print(head+vote_enc+bls_enc+desc_enc)
PY
}

_register() {
    local n=$1
    local ipc="$DATA_DIR/validator-$n/geth.ipc"
    local addr; addr=$(cat "$DATA_DIR/validator-$n/address.txt" | tr '[:upper:]' '[:lower:]')
    local body; body=$(_build_create_calldata "$n")
    local tx
    tx=$("$GETH" attach --exec \
        "eth.sendTransaction({from:'${addr}',to:'${STAKEHUB}',value:'${TX_VALUE_HEX}',gas:2000000,data:'0x${CREATE_SEL}${body}'})" \
        "$ipc" 2>/dev/null | tr -d '"')
    [[ "$tx" =~ ^0x[0-9a-fA-F]{64}$ ]] || { fail "validator-$n createValidator rejected"; return 1; }
    _wait_mined "$tx" "validator-$n createValidator" || return 1

    local padded_addr; padded_addr=$(printf '%064s' "${addr#0x}" | tr ' ' '0')
    tx=$("$GETH" attach --exec \
        "eth.sendTransaction({from:'${addr}',to:'${STAKEHUB}',value:'0xde0b6b3a7640000',gas:300000,data:'0x${DEL_SEL}${padded_addr}$(printf '%064x' 1)'})" \
        "$ipc" 2>/dev/null | tr -d '"')
    [[ "$tx" =~ ^0x[0-9a-fA-F]{64}$ ]] || { fail "validator-$n delegate rejected"; return 1; }
    _wait_mined "$tx" "validator-$n delegate"
}

# ══════════════════════════════════════════════════════════════════════════════
# PHASE 1: Register all 3 validators and wait for first breathe block
# ══════════════════════════════════════════════════════════════════════════════
echo ""
echo "══════════════════════════════════════════════════════"
echo "  PHASE 1 — register all 3 validators"
echo "══════════════════════════════════════════════════════"
echo ""

TIP_BEFORE=$(_tip)
log "Tip before registration: block #${TIP_BEFORE}"
_register 1; _register 2; _register 3

WAIT=$((BREATHE_INTERVAL + 10))
log "Waiting ${WAIT}s for first breathe block..."
sleep "$WAIT"

TIP_AFTER=$(_tip)
if [ "${TIP_AFTER:-0}" -gt "${TIP_BEFORE:-0}" ]; then
    pass "Chain live after registration: #${TIP_BEFORE} → #${TIP_AFTER}"
else
    fail "Chain stalled after registration"
fi

if _has_breathe 60; then
    pass "First breathe block fired (updateValidatorSetV2 called)"
else
    fail "No breathe block detected"
fi

ELEC=$(_election_count)
if [ "${ELEC:-0}" -eq 3 ]; then
    pass "StakeHub election set = 3 validators"
else
    fail "StakeHub election set = ${ELEC:-0} validators, expected 3"
fi

# ══════════════════════════════════════════════════════════════════════════════
# PHASE 2: Stop validator-3 to trigger downtime slashing
# ══════════════════════════════════════════════════════════════════════════════
echo ""
echo "══════════════════════════════════════════════════════"
echo "  PHASE 2 — stop validator-3, wait for misdemeanor"
echo "══════════════════════════════════════════════════════"
echo ""

VAL3_ADDR=$(cat "$DATA_DIR/validator-3/address.txt" | tr '[:upper:]' '[:lower:]')
VAL3_PID=$(cat "$DATA_DIR/validator-3/geth.pid" 2>/dev/null || echo "")

log "Stopping validator-3 (PID=${VAL3_PID}) to simulate downtime..."
if [ -n "$VAL3_PID" ]; then
    kill "$VAL3_PID" 2>/dev/null || true
    _i=0
    while kill -0 "$VAL3_PID" 2>/dev/null && [ $_i -lt 10 ]; do sleep 1; ((_i++)); done
    kill -9 "$VAL3_PID" 2>/dev/null || true
    GETH_PIDS=("${GETH_PIDS[@]/$VAL3_PID/}")
fi

log "Monitoring slash count for validator-3 (misdemeanor threshold=${MISDEMEANOR_THRESHOLD})..."
COUNT=0
MISDEMEANOR_DETECTED=0
for attempt in $(seq 1 120); do
    sleep "$SLASH_POLL"
    COUNT=$(_slash_count "$VAL3_ADDR")
    log "  block #$(_tip)  val3 slash count = ${COUNT}"
    if [ "${COUNT:-0}" -ge "$MISDEMEANOR_THRESHOLD" ]; then
        MISDEMEANOR_DETECTED=1
        break
    fi
done

if [ "$MISDEMEANOR_DETECTED" -eq 1 ]; then
    TIP_MIS=$(_tip)
    pass "Misdemeanor reached: slash count = ${COUNT} at block #${TIP_MIS}"
    pass "Chain not stalled (misdemeanor slash succeeded)"
else
    fail "Misdemeanor threshold not reached after polling (count = ${COUNT:-0})"
fi

# ══════════════════════════════════════════════════════════════════════════════
# PHASE 3: Continue until felony threshold → verify validator-3 jailed
# ══════════════════════════════════════════════════════════════════════════════
echo ""
echo "══════════════════════════════════════════════════════"
echo "  PHASE 3 — wait for felony (threshold=${FELONY_THRESHOLD})"
echo "══════════════════════════════════════════════════════"
echo ""

FELONY_DETECTED=0
JAILED=false
for attempt in $(seq 1 120); do
    sleep "$SLASH_POLL"
    COUNT=$(_slash_count "$VAL3_ADDR")
    JAILED=$(_is_jailed "$VAL3_ADDR")
    log "  block #$(_tip)  slash count = ${COUNT}  jailed = ${JAILED}"
    if [ "$JAILED" = "true" ]; then
        FELONY_DETECTED=1
        break
    fi
    if [ "${COUNT:-0}" -ge "$FELONY_THRESHOLD" ]; then
        sleep "$((SLASH_POLL * 2))"
        JAILED=$(_is_jailed "$VAL3_ADDR")
        log "  (rechecking)  block #$(_tip)  jailed = ${JAILED}"
        if [ "$JAILED" = "true" ]; then
            FELONY_DETECTED=1
            break
        fi
    fi
done

JAIL_UNTIL=$(_jail_until "$VAL3_ADDR")
if [ "$FELONY_DETECTED" -eq 1 ] && [ "$JAILED" = "true" ]; then
    pass "Felony executed: validator-3 is jailed (jailUntil=${JAIL_UNTIL})"
else
    fail "Felony not reached or validator-3 not jailed (count=${COUNT:-0} jailed=${JAILED})"
fi

# Check failedFelony event was NOT emitted (would indicate a felony revert)
FAILED_FELONY_SIG=$(_attach "web3.sha3('failedFelony(address,uint256,bytes)').slice(2)")
FAILED_FELONY_LOG=$(_attach \
"(function(){
  var logs=eth.getLogs({fromBlock:'earliest',toBlock:'latest',
    address:'${SLASHINDICATOR}',
    topics:['0x${FAILED_FELONY_SIG}']});
  return logs.length;
})()")
if [ "${FAILED_FELONY_LOG:-0}" -eq 0 ]; then
    pass "No failedFelony events — felony executed cleanly"
else
    fail "failedFelony emitted ${FAILED_FELONY_LOG} time(s) — felony reverted!"
fi

# ══════════════════════════════════════════════════════════════════════════════
# PHASE 4: Wait for breathe block with validator-3 jailed  ← critical path
# ══════════════════════════════════════════════════════════════════════════════
echo ""
echo "══════════════════════════════════════════════════════"
echo "  PHASE 4 — breathe block with jailed validator (CRITICAL)"
echo "══════════════════════════════════════════════════════"
echo ""

TIP_BEFORE_BREATHE=$(_tip)
log "Waiting for breathe block with val3 jailed (interval=${BREATHE_INTERVAL}s)..."
sleep $((BREATHE_INTERVAL + 10))
TIP_AFTER_BREATHE=$(_tip)

if [ "${TIP_AFTER_BREATHE:-0}" -gt "${TIP_BEFORE_BREATHE:-0}" ]; then
    pass "Chain live during jailed-validator breathe block: #${TIP_BEFORE_BREATHE} → #${TIP_AFTER_BREATHE}"
else
    fail "Chain STALLED during breathe block with jailed validator!"
fi

if _has_breathe 80; then
    pass "Breathe block fired (updateValidatorSetV2 succeeded with val3 excluded)"
else
    fail "No breathe block found — updateValidatorSetV2 may have reverted!"
fi

ELEC=$(_election_count)
if [ "${ELEC:-0}" -le 2 ]; then
    pass "StakeHub election set = ${ELEC:-0} (validator-3 excluded while jailed)"
else
    fail "StakeHub election set = ${ELEC:-0}, expected ≤ 2 while val3 is jailed"
fi

# ══════════════════════════════════════════════════════════════════════════════
# PHASE 5: Wait for jail time → restart validator-3 → unjail → breathe
# ══════════════════════════════════════════════════════════════════════════════
echo ""
echo "══════════════════════════════════════════════════════"
echo "  PHASE 5 — unjail and verify re-entry"
echo "══════════════════════════════════════════════════════"
echo ""

NOW=$(python3 -c "import time; print(int(time.time()))")
WAIT_UNJAIL=$(( JAIL_UNTIL - NOW + 5 ))
if [ "$WAIT_UNJAIL" -gt 0 ]; then
    log "Waiting ${WAIT_UNJAIL}s for jail time to expire (jailUntil=${JAIL_UNTIL})..."
    sleep "$WAIT_UNJAIL"
else
    log "Jail time already expired (jailUntil=${JAIL_UNTIL} ≤ now=${NOW})"
fi

log "Restarting validator-3..."
BOOTNODE="${ENODES[0]}"
_start_validator 3

log "  Waiting for validator-3 IPC..."
for _i in $(seq 1 30); do
    [ -S "$IPC3" ] && break
    sleep 1
done
[ -S "$IPC3" ] || { fail "validator-3 IPC not available after 30 s"; FAILED=1; }

# Wire validator-3 back into mesh
for j in 0 1; do
    "$GETH" attach --exec "admin.addPeer(\"${ENODES[$j]}\") + ''" \
        "$IPC3" 2>/dev/null >/dev/null || true
done
sleep 3

log "Sending unjail(val3) from validator-3..."
UNJAIL_SEL=$(_attach "web3.sha3('unjail(address)').slice(2,10)")
VAL3_PADDED="$(printf '%064s' "${VAL3_ADDR#0x}" | tr ' ' '0')"
UNJAIL_TX=$("$GETH" attach --exec \
    "eth.sendTransaction({from:'${VAL3_ADDR}',to:'${STAKEHUB}',gas:200000,data:'0x${UNJAIL_SEL}${VAL3_PADDED}'})" \
    "$IPC3" 2>/dev/null | tr -d '"')
if [[ "$UNJAIL_TX" =~ ^0x[0-9a-fA-F]{64}$ ]]; then
    _wait_mined "$UNJAIL_TX" "unjail(val3)"
else
    fail "unjail tx rejected (got: '${UNJAIL_TX}')"
fi

log "Waiting ${WAIT}s for breathe block after unjail..."
sleep "$WAIT"
TIP_FINAL=$(_tip)
pass "Chain live after unjail: tip = #${TIP_FINAL}"

if _has_breathe 80; then
    pass "Breathe block fired after unjail"
else
    fail "No breathe block after unjail"
fi

ELEC_FINAL=$(_election_count)
if [ "${ELEC_FINAL:-0}" -eq 3 ]; then
    pass "Validator-3 re-entered election set (count = 3)"
else
    fail "StakeHub election set = ${ELEC_FINAL:-0}, expected 3 after unjail"
fi

# ══════════════════════════════════════════════════════════════════════════════
# RESULT
# ══════════════════════════════════════════════════════════════════════════════
echo ""
if [ "${FAILED}" -eq 0 ]; then
    echo -e "${GREEN}ALL TESTS PASSED${NC}"
    exit 0
else
    echo -e "${RED}SOME TESTS FAILED — check output above and data/validator-1/geth.log${NC}"
    exit 1
fi
