package parliagenesis

import _ "embed"

// contract codes for ABCore Mainnet ParliaGenesis upgrade
var (
	//go:embed mainnet/ValidatorContract
	MainnetValidatorContract string
	//go:embed mainnet/SlashContract
	MainnetSlashContract string
	//go:embed mainnet/SystemRewardContract
	MainnetSystemRewardContract string
	//go:embed mainnet/LightClientContract
	MainnetLightClientContract string
	//go:embed mainnet/TokenHubContract
	MainnetTokenHubContract string
	//go:embed mainnet/RelayerIncentivizeContract
	MainnetRelayerIncentivizeContract string
	//go:embed mainnet/RelayerHubContract
	MainnetRelayerHubContract string
	//go:embed mainnet/GovHubContract
	MainnetGovHubContract string
	//go:embed mainnet/TokenManagerContract
	MainnetTokenManagerContract string
	//go:embed mainnet/CrossChainContract
	MainnetCrossChainContract string
	//go:embed mainnet/StakingContract
	MainnetStakingContract string
	//go:embed mainnet/StakeHubContract
	MainnetStakeHubContract string
	//go:embed mainnet/StakeCreditContract
	MainnetStakeCreditContract string
	//go:embed mainnet/GovernorContract
	MainnetGovernorContract string
	//go:embed mainnet/GovTokenContract
	MainnetGovTokenContract string
	//go:embed mainnet/TimelockContract
	MainnetTimelockContract string
	//go:embed mainnet/TokenRecoverPortalContract
	MainnetTokenRecoverPortalContract string
)

// contract codes for ABCore Testnet ParliaGenesis upgrade
var (
	//go:embed testnet/ValidatorContract
	TestnetValidatorContract string
	//go:embed testnet/SlashContract
	TestnetSlashContract string
	//go:embed testnet/SystemRewardContract
	TestnetSystemRewardContract string
	//go:embed testnet/LightClientContract
	TestnetLightClientContract string
	//go:embed testnet/TokenHubContract
	TestnetTokenHubContract string
	//go:embed testnet/RelayerIncentivizeContract
	TestnetRelayerIncentivizeContract string
	//go:embed testnet/RelayerHubContract
	TestnetRelayerHubContract string
	//go:embed testnet/GovHubContract
	TestnetGovHubContract string
	//go:embed testnet/TokenManagerContract
	TestnetTokenManagerContract string
	//go:embed testnet/CrossChainContract
	TestnetCrossChainContract string
	//go:embed testnet/StakingContract
	TestnetStakingContract string
	//go:embed testnet/StakeHubContract
	TestnetStakeHubContract string
	//go:embed testnet/StakeCreditContract
	TestnetStakeCreditContract string
	//go:embed testnet/GovernorContract
	TestnetGovernorContract string
	//go:embed testnet/GovTokenContract
	TestnetGovTokenContract string
	//go:embed testnet/TimelockContract
	TestnetTimelockContract string
	//go:embed testnet/TokenRecoverPortalContract
	TestnetTokenRecoverPortalContract string
)

// contract codes for ABCore Devnet (chain ID 17140) ParliaGenesis upgrade.
// Bytecodes are generated by `make devnet` with the 5 real devnet validator
// addresses baked into ValidatorContract.INIT_VALIDATORSET_BYTES.
var (
	//go:embed devnet/ValidatorContract
	DevnetValidatorContract string
	//go:embed devnet/SlashContract
	DevnetSlashContract string
	//go:embed devnet/SystemRewardContract
	DevnetSystemRewardContract string
	//go:embed devnet/LightClientContract
	DevnetLightClientContract string
	//go:embed devnet/TokenHubContract
	DevnetTokenHubContract string
	//go:embed devnet/RelayerIncentivizeContract
	DevnetRelayerIncentivizeContract string
	//go:embed devnet/RelayerHubContract
	DevnetRelayerHubContract string
	//go:embed devnet/GovHubContract
	DevnetGovHubContract string
	//go:embed devnet/TokenManagerContract
	DevnetTokenManagerContract string
	//go:embed devnet/CrossChainContract
	DevnetCrossChainContract string
	//go:embed devnet/StakingContract
	DevnetStakingContract string
	//go:embed devnet/StakeHubContract
	DevnetStakeHubContract string
	//go:embed devnet/StakeCreditContract
	DevnetStakeCreditContract string
	//go:embed devnet/GovernorContract
	DevnetGovernorContract string
	//go:embed devnet/GovTokenContract
	DevnetGovTokenContract string
	//go:embed devnet/TimelockContract
	DevnetTimelockContract string
	//go:embed devnet/TokenRecoverPortalContract
	DevnetTokenRecoverPortalContract string
)

// contract codes for ABCore Default (local self-test) ParliaGenesis upgrade
var (
	//go:embed default/ValidatorContract
	DefaultValidatorContract string
	//go:embed default/SlashContract
	DefaultSlashContract string
	//go:embed default/SystemRewardContract
	DefaultSystemRewardContract string
	//go:embed default/LightClientContract
	DefaultLightClientContract string
	//go:embed default/TokenHubContract
	DefaultTokenHubContract string
	//go:embed default/RelayerIncentivizeContract
	DefaultRelayerIncentivizeContract string
	//go:embed default/RelayerHubContract
	DefaultRelayerHubContract string
	//go:embed default/GovHubContract
	DefaultGovHubContract string
	//go:embed default/TokenManagerContract
	DefaultTokenManagerContract string
	//go:embed default/CrossChainContract
	DefaultCrossChainContract string
	//go:embed default/StakingContract
	DefaultStakingContract string
	//go:embed default/StakeHubContract
	DefaultStakeHubContract string
	//go:embed default/StakeCreditContract
	DefaultStakeCreditContract string
	//go:embed default/GovernorContract
	DefaultGovernorContract string
	//go:embed default/GovTokenContract
	DefaultGovTokenContract string
	//go:embed default/TimelockContract
	DefaultTimelockContract string
	//go:embed default/TokenRecoverPortalContract
	DefaultTokenRecoverPortalContract string
)
