name: EVM Test

on:
  push:
    branches: 
      - master

  pull_request:
    branches:
      - master
    paths:
      - '**/*.go'
      - 'go.sum'
      - 'go.mod'
      - 'tests/run-evm-tests.sh'

  workflow_dispatch:

jobs:
  evm-test:
    env:
      EVM_FIXTURES_VERSION: v5.1.0
    strategy:
      matrix:
        go-version: [1.25.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: actions/cache@v4
      with:
        # In order:
        # * Module download cache
        # * Build cache (Linux)
        # * Build cache (Mac)
        # * Build cache (Windows)
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          ~\AppData\Local\go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Cache EVM fixtures
      uses: actions/cache@v4
      with:
        path: tests/spec-tests
        key: ${{ runner.os }}-evm-fixtures-${{ env.EVM_FIXTURES_VERSION }}-${{ hashFiles('tests/run-evm-tests.sh') }}

    - name: EVM Test
      env:
        CGO_CFLAGS: "-O -D__BLST_PORTABLE__"
        CGO_CFLAGS_ALLOW: "-O -D__BLST_PORTABLE__"
        ANDROID_HOME: "" # Skip android test
        EVM_FIXTURES_VERSION: ${{ env.EVM_FIXTURES_VERSION }}
      run: |
        cd tests && bash -x run-evm-tests.sh
