name: Integration Test

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            src:
              - '**/*.go'
              - 'go.sum'
              - 'go.mod'
              - 'docker/**'
              - 'Dockerfile*'
              - 'tests/truffle/**'
              - 'Makefile'

  truffle-test:
    needs: changes
    if: needs.changes.outputs.src == 'true' || github.event_name != 'pull_request'
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Truffle test
      run: |
        make truffle-test
